export const CONFIG = {
  MAX_STEMS: 8,
  MIN_STEMS_FOR_BIND: 3,
  
  STEM_HEIGHT: 2.5,
  STEM_RADIUS: 0.03,
  STEM_MASS: 0.3,
  
  FOAM_RADIUS_TOP: 0.15,
  FOAM_RADIUS_BOTTOM: 0.25,
  FOAM_HEIGHT: 0.8,
  
  RACK_SPACING: 0.4,
  RACK_ROWS: 2,
  RACK_COLS: 6,
  
  BIND_FORCE_MIN: 5,
  BIND_FORCE_MAX: 30,
  BIND_FORCE_OPTIMAL_MIN: 12,
  BIND_FORCE_OPTIMAL_MAX: 20,
  BIND_FORCE_BREAK_THRESHOLD: 28,
  BIND_FORCE_SCATTER_THRESHOLD: 8,
  
  PHYSICS_STEPS: 3,
  PHYSICS_GRAVITY: -9.82,
  
  DESKTOP_MAX_RIGID_BODIES: 50,
  MOBILE_MAX_RIGID_BODIES: 25,
  MAX_CONTACTS: 64,
  
  TAP_COOLDOWN_MS: 300,
  
  WRAP_DURATION: 2.5,
  
  COLORS: {
    stem: 0x228B22,
    stemDark: 0x1a6b1a,
    foam: 0x90EE90,
    rack: 0x8B4513,
    ribbon: 0xFF69B4,
    wrap: 0xFFE4E1
  }
}
